### ISSUE TITLE
[SAL/Proactive] Mixing node candidates from AWS accounts

### ISSUE THREAD

**Issue by jchmielewska** [eu-nebulous/sal#4]
> register two two totally unrelated AWS accounts. Eurecat, BIBA .

> request for get node candidates filtering by cloudId == BIBA

get node candidates from BIBA account BUT, they are using an AMI that is not on BIBA account, is on Eurecat account.

Attached a request/response pair for getNodeCandidates filtering by cloud ID. The AMI (image) on the returned node candidate "ubuntu2204-cloud-with-RSA" belongs to Eurecat.

Tested it using POSTMAN agains nebulous-cd environment.

- This issue was reported by Robert and moved from Launchpad #2069716 [https://bugs.launchpad.net/nebulous/+bug/2069716

![aws](https://github.com/eu-nebulous/sal/assets/145569069/565b1408-f542-4c87-a0ba-d01716c31ebc)
](url)

**Comment by ankicabarisic** [comment]
Hi, after doing some improvements on IAAS connector to get more logs and info, it seems that fire cardentials are not good as there is Authorisation exception thrown by AWS cloud service:

```
2024-07-16 16:26:13.428 [qtp2189588-609] INFO  org.ow2.proactive.connector.iaas.cloud.provider.jclouds.JCloudsComputeServiceBuilder - Infrastructure properties: {jclouds.ssh.max-retries=7, jclouds.compute.timeout.script-complete=60000, jclouds.ec2.ami-query=state=available;image-type=machine;hypervisor=xen;virtualization-type=hvm;tag:proactive-list-label=listed-in-proactive, jclouds.compute.timeout.node-running=1200000, jclouds.request-timeout=10000, jclouds.connection-timeout=18000, jclouds.ec2.cc-ami-query=, jclouds.max-retries=5, jclouds.compute.timeout.port-open=60000}
2024-07-16 16:26:20.349 [qtp2189588-609] ERROR org.ow2.proactive.connector.iaas.util.ErrorResponse - An unexpected error occurred: While retrieving images for infrastructureID iamadummyaws-ec2_aws-fire-202406181221 :POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 -> HTTP/1.1 401 Unauthorized
org.jclouds.rest.AuthorizationException: POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 -> HTTP/1.1 401 Unauthorized
	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.refineException(ParseAWSErrorFromXmlContent.java:123) ~[sts-2.5.0.jar:2.5.0]
	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:90) ~[sts-2.5.0.jar:2.5.0]
	at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:138) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:107) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117) ~[jclouds-core-2.5.0.jar:2.5.0]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.sun.proxy.$Proxy1051.describeRegions(Unknown Source) ~[?:?]
	at org.jclouds.ec2.suppliers.DescribeRegionsForRegionURIs.get(DescribeRegionsForRegionURIs.java:50) ~[ec2-2.5.0.jar:2.5.0]
	at org.jclouds.ec2.suppliers.DescribeRegionsForRegionURIs.get(DescribeRegionsForRegionURIs.java:38) ~[ec2-2.5.0.jar:2.5.0]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:75) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57) ~[jclouds-core-2.5.0.jar:2.5.0]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:150) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.location.suppliers.derived.RegionIdsFromRegionIdToURIKeySet.get(RegionIdsFromRegionIdToURIKeySet.java:45) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.location.suppliers.derived.RegionIdsFromRegionIdToURIKeySet.get(RegionIdsFromRegionIdToURIKeySet.java:33) ~[jclouds-core-2.5.0.jar:2.5.0]
	at com.google.common.base.Suppliers$SupplierComposition.get(Suppliers.java:66) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:75) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57) ~[jclouds-core-2.5.0.jar:2.5.0]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:150) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.aws.ec2.compute.suppliers.AWSEC2ImageSupplier.get(AWSEC2ImageSupplier.java:93) ~[aws-ec2-2.5.0.jar:2.5.0]
	at org.jclouds.aws.ec2.compute.suppliers.AWSEC2ImageSupplier.get(AWSEC2ImageSupplier.java:58) ~[aws-ec2-2.5.0.jar:2.5.0]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:75) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57) ~[jclouds-core-2.5.0.jar:2.5.0]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010) ~[emailnotification-addons-14.1.0-SNAPSHOT-2024-06-26.jar:?]
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:150) ~[jclouds-core-2.5.0.jar:2.5.0]
	at org.jclouds.compute.suppliers.ImageCacheSupplier.get(ImageCacheSupplier.java:106) ~[jclouds-compute-2.5.0.jar:2.5.0]
	at org.jclouds.compute.suppliers.ImageCacheSupplier.get(ImageCacheSupplier.java:58) ~[jclouds-compute-2.5.0.jar:2.5.0]
	at org.jclouds.compute.internal.BaseComputeService.listImages(BaseComputeService.java:368) ~[jclouds-compute-2.5.0.jar:2.5.0]
	at org.ow2.proactive.connector.iaas.cloud.provider.jclouds.JCloudsProvider.getAllImages(JCloudsProvider.java:193) ~[classes/:?]
	at org.ow2.proactive.connector.iaas.cloud.CloudManager.getAllImages(CloudManager.java:94) ~[classes/:?]
	at org.ow2.proactive.connector.iaas.service.ImageService.lambda$getAllImages$0(ImageService.java:50) ~[classes/:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_382]
	at org.ow2.proactive.connector.iaas.service.ImageService.getAllImages(ImageService.java:50) ~[classes/:?]
	at org.ow2.proactive.connector.iaas.rest.ImageRest.listAllImage(ImageRest.java:58) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) ~[jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) ~[jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) ~[jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) ~[jersey-container-servlet-core-2.25.1.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) ~[jersey-container-servlet-core-2.25.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450) ~[jetty-servlet-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554) ~[jetty-servlet-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322) ~[jetty-rewrite-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.53.v20231009.jar:9.4.53.v20231009]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
Caused by: org.jclouds.http.HttpResponseException: request: POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1  [Action=DescribeRegions] failed with response: HTTP/1.1 401 Unauthorized
	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:64) ~[sts-2.5.0.jar:2.5.0]
	... 118 more

```

**Comment by ankicabarisic** [comment]
@mstietencron can you please check what is happening with FIRE cardentials?

**Comment by ankicabarisic** [comment]
The SAL release addressing this problem was released 22-07-2024
