### ISSUE TITLE
WebSocket connections Error

### ISSUE THREAD

**Issue by npapageorgopoulos12** [eu-nebulous/sal#7]
On container restart/rescale by executing:

```
kubectl scale -n nebulous-cd --replicas=0 deploy/nebulous-sal
kubectl scale -n nebulous-cd --replicas=1 deploy/nebulous-sal
```

And after new pods have been recreated, on logs:
`kubectl logs nebulous-sal-<podname> -n nebulous-cd -c sal `

i am getting the error below:
```
[New I/O worker #1] WARN  com.ning.http.client.providers.netty.handler.WebSocketProtocol - onError {}
org.atmosphere.wasync.transport.TransportNotSupported: null
        at org.atmosphere.wasync.transport.WebSocketTransport.onStatusReceived(WebSocketTransport.java:209) ~[wasync-2.1.7.jar:?]
        at com.ning.http.client.providers.netty.handler.WebSocketProtocol.handle(WebSocketProtocol.java:96) ~[async-http-client-1.9.40.jar:?]
        at com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88) ~[async-http-client-1.9.40.jar:?]

        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:?]

        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
08:16:29.824 [New I/O worker #1] ERROR org.atmosphere.wasync.transport.WebSocketTransport - WebSocket Handshake Failed
```

#### Additional Info:
I have been working on automated tests, specifically on Nebulous managed nodes.
The testing pipeline seems to fails while the test app trying to consume message from `eu.nebulouscloud.exn.sal.cluster.define` topic

**Comment by ankicabarisic** [comment]
Hello, the error you showed is a common and do not interfere with functionality of SAL.
Here you can find all the information regarding the SAL and its operation in the nebulous environment: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/deployment-manager-sal-1

In particular, you can find examples of api calls which are supported in nebulous (Postman testing scenarios) which include the definition of the defined cluster. 
Also, note that you have a special section on how the calls should be defined.
Finally, you have the explanations on how to check the SAL container logs: https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/sal-in-nebulous-k8s#sal-logs
here especially is to check the logs inside of the container (Step 3) to have more understanding of why the call failed. 

In any case, if it is defined cluster which fails, please check that you followed the step-by-step scenario for deployment in the cloud (add cloud, select node candidates, etc.) 
Note if you already sent the cluster definition with one name, the call will fail if you try to define it again. Also, depending on which cloud you are using for testing additional information is required (for now it is a must to provide the security group and ssh credentials for the AWS cloud).

In a case you will need more help on this, please provide the details of automated test steps, nebulous environment which was used and SAL logs (step 3) so i can assist you further.

**Comment by ankicabarisic** [comment]
@npapageorgopoulos12 Can you confirm that it is ok to close this issue?
